### ISSUE TITLE
Need the "compiler-rt" runtime for address sanitizer

### ISSUE THREAD

**Issue by cbuttner** [c3lang/win-llvm#3]
Related to https://github.com/c3lang/c3c/pull/1222

Specifically we need `clang_rt.asan-x86_64.lib` for address sanitizer support on windows. This library needs to be deployed next to c3c.exe so it can be linked against when `--sanitize=address` is enabled.

Here's the info on how to build:
https://clang.llvm.org/docs/AddressSanitizer.html#how-to-build

**Comment by cbuttner** [comment]
Looks like on Windows you have to build compiler-rt separately, after the LLVM build has finished.
So go into `<root>/compiler-rt`, mkdir build etc.
Configure with 
```
-G <...>
-Thost=<...>
-DCMAKE_INSTALL_PREFIX=<...>
-DCMAKE_MSVC_RUNTIME_LIBRARY=<...>
-DCMAKE_MT=<...>
<whatever other general flags are needed...>
-DLLVM_CMAKE_DIR=<LLVM install path>
```
Where the LLVM install path is what is currently packaged up (contains bin, include, lib and share)

Then build and install like LLVM
`cmake --build .`
`cmake --build . --target install` (this will install into `<install prefix>/lib/windows`)

**Comment by lerno** [comment]
All we need is the library, so presumably a second build doing that then.

**Comment by cbuttner** [comment]
I think I figured out a better way, PR coming soon.

**Comment by cbuttner** [comment]
#4 
I tested this, and it should build what is needed.

**Comment by cbuttner** [comment]
@lerno No need to build clang!

Go into `<root>/runtimes` and build with the following flags
```
set COMPILER_RT_CMAKE_CONFIGURE_FLAGS= ^
	-G "%CMAKE_GENERATOR%%CMAKE_GENERATOR_SUFFIX%" ^
	-Thost=x64 ^
	-DCMAKE_INSTALL_PREFIX=%LLVM_RELEASE_DIR%/lib/clang/18 ^
	-DCMAKE_MSVC_RUNTIME_LIBRARY=%CMAKE_CRT% ^
	-DCMAKE_MT=mt ^
	-DCMAKE_C_COMPILER_TARGET="x86_64-pc-windows-msvc" ^
	-DLLVM_ENABLE_RUNTIMES=compiler-rt ^
	-DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON ^
	-DCOMPILER_RT_BUILD_BUILTINS=OFF
```

This part is also the same
```
cmake -B . %COMPILER_RT_CMAKE_CONFIGURE_FLAGS%
cmake --build . %CMAKE_BUILD_FLAGS%
cmake --build . --target install %CMAKE_BUILD_FLAGS%
```

Confirmed this actually works quite well, including the install step.

**Comment by lerno** [comment]
Can you do a pull request for a new setup?

**Comment by cbuttner** [comment]
#6
